apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app-with-github-action
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: server
      image: nginxinc/nginx-unprivileged:alpine3.18-perl
      ports:
        - name: http
          port: 8080
      variables:
        LOG_LEVEL: INFO35
        TEST: abc
    - name: server2
      image: nginxinc/nginx-unprivileged:alpine3.18-perl
      ports:
        - name: http
          port: 8080
      variables:
        LOG_LEVEL: INFO36
        TEST: abc
    - name: server3
      image: nginxinc/nginx-unprivileged:alpine3.18-perl
      ports:
        - name: http
          port: 8080
      variables:
        LOG_LEVEL: INFO37
        TEST: abc
