apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app-with-github-action
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: server
      image: nginxinc/nginx-unprivileged:stable-alpine3.17
      ports:
        - name: http
          port: 8080
      variables:
        LOG_LEVEL: INFO75
        TEST: abc
    - name: server2
      image: nginxinc/nginx-unprivileged:stable-alpine3.17
      ports:
        - name: http
          port: 8080
      variables:
        LOG_LEVEL: INFO76
        TEST: abc
    - name: server3
      image: nginxinc/nginx-unprivileged:stable-alpine3.17
      ports:
        - name: http
          port: 8080
      variables:
        LOG_LEVEL: INFO77
        TEST: abc
