apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-mini-app-with-github-action
spec:
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: server
      image: nginxinc/nginx-unprivileged:1.22-alpine
      ports:
        - name: http
          port: 8080
      publicPort: http
      variables:
        LOG_LEVEL: ERROR
