name: CI

on:
  push:
    branches:
      - main
      - release
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    env:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Deploy API on Radix
        uses: equinor/radix-github-actions@master
        with:
          args: >
            create job
            build-deploy
            --context development
            --from-config
            -a radix-mini-app
            -b ${GITHUB_REF##*/}
            --token-environment
            -f             